service: auction9-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  httpApi: 
    cors: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

# auctions

  getAuctions:
    handler: auctions.getAuctions
    events:
      - httpApi:
          path: /auctions
          method: get

  getAuction:
    handler: auctions.getAuction
    events:
      - httpApi:
          path: /auctions/{id}
          method: get

  createAuction:
    handler: auctions.createAuction
    events:
      - httpApi:
          path: /auctions/create
          method: post

  updateAuction:
    handler: auctions.updateAuction
    events:
      - httpApi:
          path: /auctions/update/{id}
          method: put

  deleteAuction:
    handler: auctions.deleteAuction
    events:
      - httpApi:
          path: /auctions/delete/{id}
          method: put

#bids

  getBid:
    handler: bids.getBid
    events:
      - httpApi:
          path: /bids/{id}
          method: get

  getBids:
    handler: bids.getBids
    events:
      - httpApi:
          path: /bids
          method: get

  postBid:
    handler: bids.createBid
    events:
      - httpApi:
          path: /bids/create
          method: post

  deleteBid:
    handler: bids.deleteBid
    events:
      - httpApi:
          path: /bids/delete/{id}
          method: put


plugins:
  - serverless-offline